### ISSUE TITLE
Key Error Iw4m_auth_key

### ISSUE THREAD

**Issue by EdGotti** [RaidMax/IW4MAdmin-Master#17]
I have gotten most of the setup working to host the master server but the last thing im having issues with is this
<img width="356" alt="ubuntu" src="https://github.com/user-attachments/assets/e436a0c3-563b-41d3-98cd-1a1f4eca3ba3">
I am attempting to create a master server to grab ips and list them in game, i cannot find a way to grab the ips and display them in game from Raidmax so i assumed i could host my own master and connect to that but i keep getting this error

**Comment by RaidMax** [comment]
Hosting your own master server isn’t going to change anything if you’re not able to do anything with the existing one. https://master.iw4.zip/instance is all you need.

However, to resolve this runtime error you need to set the IW4MADMADMIN_AUTH_KEY environment variable to an arbitrary value. It’s used to authenticate when updating the most recent version of IW4MAdmin.

**Comment by EdGotti** [comment]
Could you tell me if there is a way to only pull server info from a certain
game. The problem I have was having is when I am able to pull info it grabs
all of the servers from every game since there isn’t separate web pages for
each game. Is there a certain port I need to use for this as well, I assumed it was 5000 but just wanted to double check. Thankyou for your help.

**Comment by RaidMax** [comment]
It’s just JSON, so all you need to do is filter on the game attribute. Someone has already done this by the way.. Your assumption is wrong as the url I linked is https which does not use port 5000.

I’m closing this as these are questions that are not  relevant to this code. You need to develop your skill set further in order to actually understand what you’re trying to do.
